project_id = "rixpasynhccgkoumpaan"

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.twilio-token]
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false

[functions.twilio-status-callback]
verify_jwt = false

[functions.twilio-recording-callback]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.sync-twilio-rates]
verify_jwt = false

[functions.og-image]
verify_jwt = false

[functions.twofa-compatibility-alert]
verify_jwt = false
