// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rixpasynhccgkoumpaan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpeHBhc3luaGNjZ2tvdW1wYWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3MzUwODQsImV4cCI6MjA4MzMxMTA4NH0.kjJZQMm1jvCN0KYz5zaFqG3aUr8Lr3ZZNZUVfq2xVC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});